[phases.setup]
nixPkgs = ["nodePackages.npm"]

[phases.install]
cmds = ["npm install"]
dependsOn = ["setup"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm run start"
